name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
  workflow_dispatch:

env:
  USE_BAZEL_VERSION: "6.4.0"

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'do-macos-build') || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Verify Installations
        run: |
          echo "--- Bazel Version ---"
          bazel --version

      - name: Build
        shell: bash
        run: |
          bazel build //...
