name: gcc

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_NAME: maliput_malidrive
  ROS_DISTRO: foxy

# Cancel previously running PR jobs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  bazel:
    name: Compile and Test (Bazel)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-bazel-ci:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        bazel build //...
        bazel test //...

  cmake:
    name: Compile and Test (CMake)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.3
    - uses: ros-tooling/action-ros-ci@v0.2
      id: action_ros_ci_step
      with:
        package-name: ${{ env.PACKAGE_NAME }}
        target-ros2-distro: ${{ env.ROS_DISTRO }}
        vcs-repo-file-url: ${GITHUB_WORKSPACE}/.github/dependencies.repos
